import { Montserrat, Inknut_Antiqua} from "next/font/google";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";




const inknut = Inknut_Antiqua({
    subsets: ['latin'],
    weight: ['400', '600', '700'],
    variable: '--font-inknut-antiqua',
    display: 'swap',
  })
  
  const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-montserrat',
    display: 'swap',
  })

  
  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };


export default function PageLayout({ children }) {
  return (
    <div className={`${inknut.variable} ${montserrat.variable} antialiased`}>
       
      <SidebarProvider>
      <AppSidebar />
      <main className="w-full">
      <SidebarInset> 
        {children}
        </SidebarInset>
        </main>
      </SidebarProvider>
     
    </div>
  );
}
