import { Montserrat, Inknut_Antiqua} from "next/font/google";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const inknut = Inknut_Antiqua({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-inknut-antiqua',
  display: 'swap',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PageLayout({ children }) {
  return (
    <div className={`${inknut.variable} ${montserrat.variable} antialiased min-h-screen w-full flex flex-col`}>
      <SidebarProvider className="flex-1 flex">
        <AppSidebar />
        <main className="flex-1 flex flex-col min-w-0 overflow-hidden">
          <SidebarInset className="flex-1 flex flex-col h-full"> 
            <div className="flex-1 w-full h-full overflow-auto">
              {children}
            </div>
          </SidebarInset>
        </main>
      </SidebarProvider>
    </div>
  );
}