import { Montserrat, Inknut_Antiqua } from "next/font/google";

import Navbar_dashboard from "@/components/dashboard/Navbar_dashboard";
import AppSideBar from "@/components/dashboard/AppSideBar";
import { SidebarProvider } from "@/components/ui/sidebar";

const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inknut-antiqua",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PageLayout({ children }) {
  return (
    <div className={`${inknut.variable} ${montserrat.variable} antialiased`}>
      <div id="full-layout" className="flex flex-col gap-0 min-h-screen">
        <header
          id="navbar-section"
          className="hidden md:flex items-center w-full justify-between fixed top-0 z-50 h-16 px-4 border-b border-gray-200 bg-white"
        >
          <Navbar_dashboard />
        </header>
        <SidebarProvider
          style={{
            "--sidebar-width": "20rem",
            "--sidebar-width-mobile": "10rem",
          }}
        >
          <div
            id="sidebar-main"
            className="flex md:flex-row flex-1 overflow-hidden min-h-screen"
          >
            <aside className="flex-none w-16 md:basis-36 lg:basis-60 md:max-w-md h-full bg-red-500">
              <AppSideBar />
            </aside>
            <main className="flex-1 p-5 overflow-y-auto min-h-screen mt-16">
              <div className="flex gap-x-2">
                <p>Colll</p>
                {children}
              </div>
            </main>
          </div>
        </SidebarProvider>
      </div>
    </div>
  );
}
