
import { Montserrat, Inknut_Antiqua } from "next/font/google";

import Navbar_dashboard from "@/components/dashboard/Navbar_dashboard";


const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inknut-antiqua",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PageLayout({ children }) {
  return (
    <div className={`${inknut.variable} ${montserrat.variable} antialiased`}>
      <div className="flex flex-col">
        <div className="hidden md:flex">
          <Navbar_dashboard />
        </div>
        <div className="flex gap-4 p-4">
          <div></div>
          <main className="flex">
            <span>{children}</span>
          </main>
        </div>
      </div>
    </div>
  );
}
